In [1]:
impoer numpy as np

SyntaxError: invalid syntax (<ipython-input-1-60ea92897071>, line 1)

In [2]:
import numpy as np

In [3]:
array1 = np.array(range(30))
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [4]:
array1.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [5]:
np.where(array1%6==1)

(array([ 1,  7, 13, 19, 25]),)

In [7]:
np.where (array1%6==1)[0]

array([ 1,  7, 13, 19, 25])