作業目標<br>
計算有缺失值的資料，統計量實作<br>
作業重點<br>
當遇到缺失值有函式可以處理，不須額外寫程式刪除<br>
計算統計量時不能出現缺失值

題目:<br>
english_score = np.array([55,89,76,65,48,70])<br>
math_score = np.array([60,85,60,68,np.nan,60])<br>
chinese_score = np.array([65,90,82,72,66,77])<br>
上3列共六位同學的英文、數學、國文成績，第一個元素代表第一位同學，舉例第一位同學英文55分、數學60分、國文65分，今天第五位同學因某原因沒來考試，導致數學成績缺值，運用上列數據回答下列問題。<br>
1. 請計算各科成績平均、最大值、最小值、標準差，其中數學缺一筆資料可忽略?
2. 第五位同學補考數學後成績為55，請計算補考後數學成績平均、最大值、最小值、標準差?
3. 用補考後資料找出與國文成績相關係數最高的學科?

In [1]:
import numpy as np

In [2]:
english_score = np.array([55,89,76,65,48,70])
math_score = np.array([60,85,60,68,np.nan,60])
chinese_score = np.array([65,90,82,72,66,77])

In [3]:
#1. 請計算各科成績平均、最大值、最小值、標準差，其中數學缺一筆資料可忽略?

In [ ]:
#ENGLISH

In [3]:
np.mean(english_score)

67.16666666666667

In [4]:
np.max(english_score)

89

In [5]:
np.min(english_score)

48

In [6]:
np.var(english_score)

180.47222222222226

In [ ]:
#MATH

In [7]:
np.nanmean(math_score)

66.6

In [8]:
np.nanmax(math_score)

85.0

In [9]:
np.nanmin(math_score)

60.0

In [10]:
np.nanvar(math_score)

94.24000000000002

In [ ]:
#CHINESE

In [11]:
np.mean(chinese_score)

75.33333333333333

In [12]:
np.max(chinese_score)

90

In [13]:
np.min(chinese_score)

65

In [14]:
np.var(chinese_score)

77.88888888888889

In [4]:
#2. 第五位同學補考數學後成績為55，請計算補考後數學成績平均、最大值、最小值、標準差?

In [15]:
math_score[4]=55
math_score

array([60., 85., 60., 68., 55., 60.])

In [16]:
np.mean(math_score)

64.66666666666667

In [17]:
np.max(math_score)

85.0

In [18]:
np.min(math_score)

55.0

In [19]:
np.var(math_score)

97.22222222222223

In [5]:
#3. 用補考後資料找出與國文成績相關係數最高的學科?

In [20]:
np.corrcoef(chinese_score,math_score)

array([[1.        , 0.74056803],
       [0.74056803, 1.        ]])

In [21]:
np.corrcoef(chinese_score,english_score)

array([[1.        , 0.97792828],
       [0.97792828, 1.        ]])